# nautobot_api_config.yaml
api_endpoints:

  statuses:
    path: "/api/extras/statuses/"
    model_name: "extras.status"
    get_params:
      - name
    create_params:
      - name
      - slug
      - color


  location_types:
    path: "/api/dcim/location-types/"
    model_name: "dcim.location_type"
    get_params:
      - name
    create_params:
      - name
      - slug
      - nestable
      - parent:
          endpoint: location_types
          lookup: name
      - content_types:
        resolve:
          type: content_type
          value: 
            - dcim.device
            - dcim.rack

  locations:
    path: "/api/dcim/locations/"
    model_name: "dcim.location"
    get_params:
      - name
    create_params:
      - name
      - location_type:
          endpoint: location_types
          lookup: name
      - parent:
          endpoint: locations
          lookup: name
      - status:
          endpoint: statuses
          lookup: name

  manufacturers:
    path: "/api/dcim/manufacturers/"
    model_name: "dcim.manufacturer"
    get_params:
      - name
    create_params:
      - name
      - slug

  platforms:
    path: "/api/dcim/platforms/"
    model_name: "dcim.platform"
    get_params:
      - name
    create_params:
      - name
      - slug
      - manufacturer:
          endpoint: manufacturers
          lookup: name
      - network_driver
      - napalm_driver
      - network_driver_mappings


  device_types:
    path: "/api/dcim/device-types/"
    model_name: "dcim.device_type"
    get_params:
      - model
    create_params:
      - model
      - slug
      - part_number
      - manufacturer:
          endpoint: manufacturers
          lookup: name

  devices:
    path: "/api/dcim/devices/"
    model_name: "dcim.device"
    get_params:
      - name
    create_params:
      - name
      - device_type:
          endpoint: device_types
          lookup: model
      - platform:
          endpoint: platforms
          lookup: name
      - location:
          endpoint: locations
          lookup: name
      - status:
          endpoint: statuses
          lookup: name
      - serial

  interfaces:
    path: "/api/dcim/interfaces/"
    model_name: "dcim.interface"
    get_params:
      - device_id
      - name
    create_params:
      - name
      - type
      - enabled
      - mtu
      - mac_address
      - device:
          endpoint: devices
          lookup: name

  ip_addresses:
    path: "/api/ipam/ip-addresses/"
    model_name: "ipam.ipaddress"
    get_params:
      - address
    create_params:
      - address
      - status:
          endpoint: statuses
          lookup: name
      - assigned_object:
          type_field: assigned_object_type
          id_field: assigned_object_id

  cables:
    path: "/api/dcim/cables/"
    model_name: "dcim.cable"
    get_params:
      - termination_a_id
      - termination_b_id
    create_params:
      - termination_a
      - termination_b
      - status:
          endpoint: statuses
          lookup: name