# nautobot_api_config.yaml
api_endpoints:

  statuses:
    path: "/api/extras/statuses/"
    model_name: "extras.status"
    get_params:
      - name
    create_params:
      - name
      - slug
      - color


  location_types:
    path: "/api/dcim/location-types/"
    model_name: "dcim.location_type"
    get_params:
      - name
    create_params:
      - name
      - slug
      - nestable
      - parent:
          endpoint: location_types
          lookup: name
      - content_types:
        resolve:
          type: content_type
          value: 
            - dcim.device
            - dcim.rack
            - dcim.rackgroup            

  locations:
    path: "/api/dcim/locations/"
    model_name: "dcim.location"
    get_params:
      - name
    create_params:
      - name
      - location_type:
          endpoint: location_types
          lookup: name
      - parent:
          endpoint: locations
          lookup: name
      - status:
          endpoint: statuses
          lookup: name

  manufacturers:
    path: "/api/dcim/manufacturers/"
    model_name: "dcim.manufacturer"
    get_params:
      - name
    create_params:
      - name
      - slug

  platforms:
    path: "/api/dcim/platforms/"
    model_name: "dcim.platform"
    get_params:
      - name
    create_params:
      - name
      - slug
      - manufacturer:
          endpoint: manufacturers
          lookup: name
      - network_driver
      - napalm_driver
      - network_driver_mappings


  device_types:
    path: "/api/dcim/device-types/"
    model_name: "dcim.device_type"
    get_params:
      - model
    create_params:
      - model
      - slug
      - part_number
      - manufacturer:
          endpoint: manufacturers
          lookup: name

  roles:
    path: /api/extras/roles/
    model_name: extras.role
    get_params:
      - name
    create_params:
      - name
      - content_types:
        resolve:
          type: content_type
          value: 
            - dcim.device
            - dcim.rack
            - dcim.rackgroup

  rack-groups:
    path: /api/dcim/rack-groups
    model_name: dcim.rackgroup
    get_params:
      - name
    create_params:
      - name   
      - location:
          endpoint: location
          lookup: name


  racks:
    path: /api/dcim/racks
    model_name: dcim.rack
    get_params:
      - name
    create_params:
      - name   
      - location:
          endpoint: location
          lookup: name
      - status:
          endpoint: statuses
          lookup: name
      - rack-groups:    
          endpoint: rack-groups
          lookup: name


  secrets-groups-associations:
    path: /api/extras/secrets-groups-associations
    model_name: extras.secretsgroupassociation
    get_params:
      - access_type
      - secret_type
      - secrets_group
      - secret            
    create_params:
      - access_type
      - secret_type
      - secrets_group:
          endpoint: secrets-group
          lookup: name      
      - secret:
          endpoint: secrets
          lookup: name 

  secrets-groups:
    path: /api/extras/secrets-groups
    model_name: extras.secretsgroup
    get_params:
      - name
    create_params:
      - name     

  secrets:
    path: /api/extras/secrets
    model_name: extras.secrets
    get_params:
      - name
    create_params:
      - name
      - provider